### ISSUE TITLE
Inactive layers introduce NaNs

### ISSUE THREAD

**Issue by cbegeman** [E3SM-Project/Omega#321]
For the test case https://github.com/E3SM-Project/polaris/pull/353 where there are inactive layers (`MaxLayerCell` < `NVertLayers` - 1), NaNs are introduced from the boundary. Thanks to @brian-oneill for identifying this issue.

**Comment by brian-oneill** [comment]
These are caused by quantities (specifially tracers and vorticities) that are normalized by the layer thickness. The thickness is 0 in inactive layers, so these quantities become NaNs. Since `0 * NaN = NaN`, the edge masks don't catch them and they propagate into the domain as the simulation advances. These should be resolved by moving to hierarchical parallelism and restricting the vertical loops to only active layers.

The NaNs are introduced here:
https://github.com/E3SM-Project/Omega/blob/43eb7639a270bee7ceafb91d7e0efb5b9f889487/components/omega/src/ocn/auxiliaryVars/VorticityAuxVars.h#L49-L59
https://github.com/E3SM-Project/Omega/blob/43eb7639a270bee7ceafb91d7e0efb5b9f889487/components/omega/src/timeStepping/TimeStepper.cpp#L461-L469
https://github.com/E3SM-Project/Omega/blob/43eb7639a270bee7ceafb91d7e0efb5b9f889487/components/omega/src/timeStepping/TimeStepper.cpp#L519-L524

The vorticity normalizations should be resolved by #314, but not the tracer normalizations since this PR doesn't touch the `TimeStepper` loops yet. Not sure if we want to add some guards like:
```
if (LayerThickness == 0) InvLayerThickness = 0
```
since they won't be necessary once the calculations in inactive layers are skipped entirely.

**Comment by cbegeman** [comment]
> Not sure if we want to add some guards like:
if (LayerThickness == 0) InvLayerThickness = 0
since they won't be necessary once the calculations in inactive layers are skipped entirely.

That's a good question. I'm wondering if we _don't_ want to do this because it may obscure if/when we erroneously access inactive vertical layers.

**Comment by mwarusz** [comment]
> That's a good question. I'm wondering if we don't want to do this because it may obscure if/when we erroneously access inactive vertical layers.

I agree, it would be great if we could avoid accessing inactive layers. I have updated #314 to limit vertical loops in the time stepping code. Hopefully, that PR can fix this issue once it gets merged.

**Comment by cbegeman** [comment]
@mwarusz and @brian-oneill I just wanted to put on your radar that https://github.com/E3SM-Project/Omega/pull/314 did not resolve this issue as we had hoped (at least based on the results of the barotropic channel case https://github.com/E3SM-Project/polaris/pull/353, which still has NaNs)

**Comment by cbegeman** [comment]
@vanroekel Thanks for pointing out https://github.com/E3SM-Project/Omega/pull/335#issuecomment-3854459566. So I think we can wait to retest @brian-oneill.
